language: java
jdk:
  - oraclejdk8
env:
  matrix:
    - PROFILE=ci
    - PROFILE=spring42-next
    - PROFILE=spring43-next
cache:
  directories:
    - $HOME/.m2
sudo: false
install: true
script: "mvn clean test -P${PROFILE}"